# Generated by Django 5.1.15 on 2026-04-18 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('posture_angle', models.FloatField(blank=True, null=True)),
                ('posture_status', models.CharField(blank=True, max_length=32)),
                ('posture_mode', models.CharField(blank=True, max_length=16)),
                ('blink_rate', models.FloatField(default=0)),
                ('blink_count', models.IntegerField(default=0)),
                ('perclos', models.FloatField(default=0)),
                ('breath_rate', models.FloatField(default=0)),
                ('breath_phase', models.CharField(blank=True, max_length=16)),
                ('emotion', models.CharField(blank=True, max_length=16)),
                ('emotion_confidence', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='camera_app.analysissession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
