# Generated by Django 5.1.15 on 2026-04-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feeling', models.IntegerField()),
                ('fatigue_at_report', models.FloatField(blank=True, null=True)),
                ('stress_at_report', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='camera_app.analysissession')),
            ],
        ),
    ]
